name: build by commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Verify go.mod is sane
      run: go mod tidy && git diff --no-patch --exit-code

    - name: Run code lint
      run: make lint

    - name: Install dependencies
      run: go mod download

    - name: Verify build
      run: make dev

    - name: Make binaries
      if: contains(github.ref, 'tags')
      run: |
        set -euo pipefail
        sudo apt update
        sudo apt install -y upx
        hack/install-gox.sh
        make deploy

    - name: Create release
      if: contains(github.ref, 'tags')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binaries to release
      if: contains(github.ref, 'tags')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # hacky glob pattern because this does not accept multiple patterns
        file: out/kubectl-nsenter-{amd64,arm64}-*.{tar,zip}*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
